### ISSUE TITLE
Create Quest 1

### ISSUE THREAD

**Issue by Dominika29** [Dominika29/projekt-psio#1]
## Task Overview

**Task Name:**
Create quest 1

**Task Description:**
Create sprites, place them in right places on the map. Create hero ability to move sprites and drop them.

## Subtasks

- [x] Subtask 1: Create sprites in right places.
- [x] Subtask 2: Make them interact with the hero.
- [x] Subtask 3: Make them unmovable when they are put in the right spot.
- [x] Subtask 4: Make subwindow close itself after ending quest.
- [x] Subtask 5: Create new quest sprite above new enemy.

## Resources and Dependencies

**Resources:**
Use assets from file folder.

## Timeline

**Start Date:**
30.05.2024

**Due Date:**
3.06.2024

**Comment by Dominika29** [comment]
4 days delayed, code needs optimalization
