### ISSUE TITLE
Create Quest 2

### ISSUE THREAD

**Issue by Dominika29** [Dominika29/projekt-psio#2]
## Task Overview

**Task Name:**
Create quest 2

**Task Description:**
Second quest will be a fight with an enemy. We need to create a map and system of fight. 

## Subtasks

- [x] Subtask 1: Create enemy sprite and its animations.
- [x] Subtask 2: Make hero animations of fight.
- [x] Subtask 3: Interactions; hero with enemy.
- [x] Subtask 4: Add HP bars and make them work.
- [x] Subtask 5: Make subwindow close after killing enemy or restart-window after hero dying.
- [x] Subtask 6: Create new quest sprite above new enemy.

## Resources and Dependencies

**Resources:**
Find new assets of enemies. Hero fight animations - use from the folder.

## Timeline

**Start Date:**
02.06.2024

**Due Date:**
05.06.2024
